### ISSUE TITLE
Move current file to another folder after template selection

### ISSUE THREAD

**Issue by lifehaschanged** [numeroflip/obsidian-auto-template-prompt#19]
Hi @numeroflip !

Big thanks for the plugin!

When I create a new note, I often need to move the file to another folder. 
I would be great if you can add an option. There is an Obsidian command:
"Move current file to another folder" that opens this popup

![grafik](https://github.com/numeroflip/obsidian-auto-template-trigger/assets/81463128/589b320e-dc79-4e2d-a8cb-df90753c418d)

Do you think it's possible to give us a new option that after the template selection from your plugin this command from above will run automatically?

**Comment by numeroflip** [comment]
Hey @lifehaschanged, thanks for suggesting this feature. 
It seems like a very sensible thing to do, and it's definitely worth considering.

Although since this plugin is designed to be lightweight, and simple, this feature might be a bit out of scope. 

Have you tried this plugin? : https://github.com/farux/obsidian-auto-note-mover
I believe it's an excellent opportunity to combine 2 plugins to arrive at this desired behavior. Eg you can add a rule, so the presence of a given tag, will automatically move a note to a given folder, and add that tag into one of the templates. This way every time you select that template, the note will be moved to the assigned folder.

Eg you create a new note -> select a Template -> it gets automatically moved to the folder, if the template's content is such as "auto-note-mover" moves it there. 

That's just an idea, so let me know, if it might serve your needs, or if you would still prefer this kind of functionality in a single plugin, so we can further discuss the details.  IDK. In general, I would like to avoid adding a lot of extra functionality to keep it simple, but I'm open to it, so please let me know
